version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - DATABASE_URL=sqlite:///tarefas.db
    volumes:
      - .:/app
      - db_data:/app/tarefas.db

volumes:
  db_data:
