services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - DATABASE_URL=sqlite:///data/tarefas.db
    volumes:
      - .:/app
      - db:/app/data

volumes:
  db:
