services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - DATABASE_URL=sqlite:///tarefas.db
    volumes:
      - .:/app
      - app-tarefas:/app/instance

volumes:
  app-tarefas:
