version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - DATABASE_URL=sqlite:///tarefas.db
    volumes:
      - .:/app
      - ./data:/app/data
    command: flask run --host=0.0.0.0
